version: 2
updates:
  - package-ecosystem: npm
    directory: /theonefile_verse
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /theonefile_verse
    schedule:
      interval: weekly
